#!/usr/bin/env python

import math

import numpy as np

import rclpy
from rclpy.node import Node

from tf2_ros.transform_listener import TransformListener
from tf2_ros.buffer import Buffer
from tf2_ros import TransformBroadcaster
from tf_transformations import quaternion_from_euler, euler_from_quaternion

from geometry_msgs.msg import TransformStamped, Twist
from robp_interfaces.msg import Encoders
from nav_msgs.msg import Path
from geometry_msgs.msg import PoseStamped

from robp_interfaces.msg import DutyCycles

import tf2_geometry_msgs


class Controller(Node):
    """
    Directs the robot iteratively towards a position defined in topic /path/nextpos (TransformStamped)
    needs continous republishing of the goal position in topic
    """

    def __init__(self):
        super().__init__("path_follower")  # Call the superclass constructor
        self.buffer = Buffer()
        self.listener = TransformListener(self.buffer, self, spin_thread=False)
        self.create_subscription(
            TransformStamped, "/path/nextpos", self.nextpos_callback, 10
        )
        self.publisher = self.create_publisher(DutyCycles, "/motor/duty_cycles", 10)
        self.goal_position = TransformStamped()

        self.goal_margin_translational = 0.05
        self.goal_margin_rotational = math.pi / 6

        self.speed_factor = 1

        self.speed_lin = 1.5
        self.speed_rot = 0.75

        self.p_rotation = (
            10  # 0 !< p_rotation !< 2base/(h*radius) =  12.599/h h:=sampling time
        )
        self.p_translation = (
            30  # 0 !< p_translation !< 2/(h*radius) = 40.642/h h:=sampling time
        )

    def nextpos_callback(self, msg: TransformStamped):
        self.goal_position = msg
        # init
        time = msg.header.stamp
        robot_frame = msg.child_frame_id
        goal_frame = "base_link"

        goal_margin_translational = 0.05
        goal_margin_rotational = math.pi / 6

        # cmd_vel = Twist()
        # cmd_vel.linear.x = 0.0
        # cmd_vel.angular.z = 0.0

        # Wait for the transform asynchronously
        compared_transform = self.buffer.wait_for_transform_async(
            target_frame=goal_frame, source_frame=robot_frame, time=time
        )
        rclpy.spin_until_future_complete(self, compared_transform, timeout_sec=0.5)

        # Check if the future completed successfully
        if not compared_transform.done():
            self.get_logger().error(
                f"Transform future did not complete successfully between {robot_frame} and {goal_frame}."
            )
            return
        else:
            finished_transform = compared_transform.result()
            comp_translation = finished_transform.transform.translation
            comp_rotation = finished_transform.transform.rotation
            distance_to_point = math.sqrt(comp_translation.x**2 + comp_translation.y**2)

            theta_goal = euler_from_quaternion(comp_rotation)[2]
            theta_dir = math.atan2(comp_translation.y, comp_translation.x)
            delta_theta = theta_dir

        try:
            if delta_theta > goal_margin_rotational:
                w = self.p_rotation * delta_theta
                v = 0
                # v = self.p_trans_rotation * (cos(theta_))
                print(f"Rotating towards {[comp_translation.x, comp_translation.y]}")
            elif distance_to_point > goal_margin_translational:
                v = self.p_translation * (
                    comp_translation.x * math.cos(delta_theta)
                    + comp_translation.y * math.sin(delta_theta)
                )
                # w = self.p_rot_translation * (math.sin(delta_theta*))
                w = 0
                print(f"Moving towards {[comp_translation.x, comp_translation.y]}")
            elif (distance_to_point < goal_margin_translational) and (
                theta_goal > goal_margin_rotational
            ):
                # w = self.p_rotation*theta_goal
                print(f"AT GOAL\nROTATING DIST: {theta_goal}")
            print(f"v: {v}, w: {w}")

            # Damping
            v_damper = 1
            w_damper = 1
            v = v * v_damper
            w = w * w_damper

            # Convert to duty cycles
            motor_msg = DutyCycles()
            motor_msg.duty_cycle_left = v - 0.5 * w
            motor_msg.duty_cycle_right = v + 0.5 * w

            motor_msg.header.stamp = msg.header.stamp

            self.publisher.publish(motor_msg)

            self.get_logger().info(f"Published!")

            return
        except Exception as ex:
            # Log any errors (this will only log broadcasting issues now)
            self.get_logger().error(
                f"Failed to move towards position: {msg.transform} \n {ex}"
            )
            return

    # def do_go_to_point(self):

    #     time = self.get_clock().now().to_msg()
    #     robot_frame = "goal_position"
    #     goal_frame = "base_link"

    #     margin_rotate_first = 0.2  # for points below this distance the robot will rotate first without going forward

    #     cmd_vel = Twist()
    #     cmd_vel.linear.x = 0.0
    #     cmd_vel.angular.z = 0.0

    #     # # Wait for the transform asynchronously
    #     compared_transform = self.buffer.wait_for_transform_async(
    #         target_frame=goal_frame, source_frame=robot_frame, time=time
    #     )
    #     rclpy.spin_until_future_complete(self, compared_transform, timeout_sec=1)

    #     # Check if the future completed successfully
    #     if not compared_transform.done():
    #         self.get_logger().error(
    #             f"Transform future did not complete successfully between {robot_frame} and {goal_frame}."
    #         )
    #         return
    #     else:
    #         finished_transform = compared_transform.result()
    #         comp_translation = finished_transform.transform.translation
    #         comp_rotation = finished_transform.transform.rotation
    #         distance_to_point = math.sqrt(comp_translation.x**2 + comp_translation.y**2)

    #     try:
    #         # check whether it is already at goal point
    #         if distance_to_point < self.goal_margin_translational * 2:
    #             print(f"Already at goal point")
    #             # check whether orientation is correct, rotate if not
    #             if abs(comp_rotation.z) < self.goal_margin_rotational:
    #                 cmd_vel.linear.x = 0.0
    #                 cmd_vel.angular.z = 0.0
    #                 self.get_logger().info("Position already reached.")
    #             elif comp_rotation.z > 0:
    #                 cmd_vel.angular.z = self.speed_rot
    #                 self.get_logger().info(
    #                     "Position already reached. Orientation to be fixed"
    #                 )
    #             elif comp_rotation.z < 0:
    #                 cmd_vel.angular.z = -self.speed_rot
    #                 self.get_logger().info(
    #                     "Position already reached. Orientation to be fixed"
    #                 )
    #         # if not already at goal point
    #         else:
    #             if (
    #                 (comp_translation.y < 0)
    #                 and (abs(comp_translation.y) > self.goal_margin_translational)
    #                 and (comp_translation.x > 0)
    #             ):
    #                 cmd_vel.angular.z = -self.speed_rot
    #                 print("turning right")
    #                 print(f"Difference: {abs(comp_translation.y)}")

    #             elif (
    #                 (comp_translation.y > 0)
    #                 and (abs(comp_translation.y) > self.goal_margin_translational)
    #                 and (comp_translation.x > 0)
    #             ):
    #                 cmd_vel.angular.z = self.speed_rot
    #                 print("turning left")
    #                 print(f"Difference: {abs(comp_translation.y)}")

    #             elif comp_translation.x < 0:
    #                 cmd_vel.angular.z = self.speed_rot
    #                 print("turning around")
    #                 print(
    #                     f"Distance to position: {[comp_translation.x, comp_translation.y]}"
    #                 )

    #             else:
    #                 cmd_vel.linear.x = self.speed_lin
    #                 print("move ahead")
    #                 print(
    #                     f"Distance to position: {[comp_translation.x, comp_translation.y]}"
    #                 )
    #             self.publisher.publish(cmd_vel)

    #     except Exception as ex:
    #         self.get_logger().error(ex)


def main():
    rclpy.init()
    node = Controller()
    # try:
    #     while rclpy.ok():
    #         rclpy.spin_once(node)
    #         node.do_go_to_point()
    # except KeyboardInterrupt:
    #     pass
    rclpy.spin(node)

    rclpy.shutdown()


if __name__ == "__main__":
    main()
